name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build Application
    runs-on: windows-latest  # Running on Windows

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --no-restore --configuration Release

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4  # Updated to v4
      with:
        name: build-output
        path: |
          **/bin/Release/
          **/obj/Release/
        retention-days: 1  # Optional: Set how long artifacts are kept

  test:
    name: Run Tests
    runs-on: windows-latest
    needs: build  # Runs only if build succeeds

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Download Build Artifacts
      uses: actions/download-artifact@v4  # Updated to v4
      with:
        name: build-output
        path: .

    - name: Run Unit Tests
      run: dotnet test --no-build --verbosity normal
