name: .NET CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DOTNET_VERSION: 8.0.x

jobs:
  build:
    name: Build Application
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --configuration Release --no-restore

    - name: Publish API
      run: dotnet publish -c Release -o ./publish-api ./Hackathon.API/Hackathon.API.csproj

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: |
          ./publish-api/
        retention-days: 1

  test:
    name: Run Tests
    runs-on: windows-latest
    needs: build

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-output
        path: .

    - name: Run Unit Tests
      run: dotnet test --configuration Release --no-build --verbosity normal

  deploy:
    name: Deploy to Azure via FTP
    runs-on: windows-latest
    needs: test  # Só faz deploy se os testes passarem

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-output
        path: .

    - name: Deploy API via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4
      with:
        server: "ftps://waws-prod-yt1-015.ftp.azurewebsites.windows.net/site/wwwroot"
        username: "Hackathon-API\\$Hackathon-API"
        password: "kZvpbobno7QHYB2Q8S4bTZpPXtGNg9MEWooHSisqu8iNsiQn5Dajs56w2iRt"
        local-dir: ./publish-api/
        server-dir: /site/wwwroot/
